import React from "react";
import "./Report.css";

function Report() {
  return (
    <div className="ReportBody">
      ReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReportReport
    </div>
  );
}

export default Report;
